### ISSUE TITLE
Clicking on Create->Lane in an empty world causes editor to panic.

### ISSUE THREAD

**Issue by arjo129** [open-rmf/rmf_site#130] opened 2023-05-22 03:23 UTC
### Description of the bug
Clicking on `Create->Lane` in the editor when no anchor is selected causes the editor to panic. The offending line is here:
https://github.com/open-rmf/rmf_site/blob/f796e44ce5a1d13a2878b5cc2cd7d93de0bbee0b/rmf_site_editor/src/interaction/anchor.rs#L44

### Steps to reproduce the bug

1. File -> new
2. Click on create->lane.
3. Click on the empty space.

### Expected behavior
A panic feels extreme. The system should gracefully do nothing or give a warning at this point

### Actual behavior
The application panics.

**Comment by luca-della-vedova** [comment] 2023-05-22 03:25
Yea I think this is fixed in some branch, the problem is that an empty world has no level hence the lane creation fails, a proper way would be to initialize an empty world with an empty level as well

**Comment by mxgrey** [comment] 2023-05-22 07:42
I fully agree that an empty level `L1` should automatically be created when a new world is created.

**Closed** 2023-07-07 04:52 UTC
Labels: bug
